name = "SCoBA"
uuid = "094a3a66-d13f-40de-88af-6877f7c9e9ac"
authors = ["Shushman <shushmanchoudhury@gmail.com>"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
Hungarian = "e91730f6-4275-51fb-a7a0-7064cfbd3b39"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MCTS = "e12ccd36-dcad-5f33-8774-9175229e7b33"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPPolicies = "182e52fb-cfd0-5e46-8c26-fd0667c990f4"
POMDPSimulators = "e0d0a172-29c6-5d4e-96d0-f262df5d01fd"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TOML = "191fdcea-f9f2-43e0-b922-d33f71e2abc3"
TabularTDLearning = "df77095f-98f0-51e5-a706-d0ff5a5ad33f"

[compat]
ArgParse = "0.6.2"
julia = ">= 1.3"
